### ISSUE TITLE
JavaBuilder Throws NullPointerException

### ISSUE THREAD

**Issue by jGleitz** [vitruv-tools/Vitruv-Domains-ComponentBasedSystems#77]
I just found this and had no time to investigate yet:

```
java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at tools.vitruv.framework.ui.monitorededitor.VitruviusProjectBuilder.initializeBuilder(VitruviusProjectBuilder.java:42)
	at tools.vitruv.framework.ui.monitorededitor.VitruviusProjectBuilder.build(VitruviusProjectBuilder.java:63)
	at tools.vitruv.domains.java.builder.VitruviusJavaBuilder.build(VitruviusJavaBuilder.java:27)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:845)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:228)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:356)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:482)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:565)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:603)
	at org.eclipse.core.internal.resources.Project.build(Project.java:124)
	at tools.vitruv.framework.ui.monitorededitor.ProjectBuildUtils.buildIncrementally(ProjectBuildUtils.java:59)
	at tools.vitruv.framework.ui.monitorededitor.ProjectBuildUtils.buildAllProjectsIncrementally(ProjectBuildUtils.java:38)
	at tools.vitruv.domains.java.builder.JavaBuildOnEclipseStartup.earlyStartup(JavaBuildOnEclipseStartup.java:20)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:79)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:55)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench$40.run(Workbench.java:2667)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
10   [Worker-0: Executing the early startup extensions] ERROR tools.vitruv.domains.java.builder.JavaBuildOnEclipseStartup  - Could not perform initial build for all projects
java.lang.IllegalStateException: Could not run builder tools.vitruv.domains.java.builder.JavaBuilder.id for project Vitruv-Applications-ComponentBasedSystems
	at tools.vitruv.framework.ui.monitorededitor.ProjectBuildUtils.buildIncrementally(ProjectBuildUtils.java:63)
	at tools.vitruv.framework.ui.monitorededitor.ProjectBuildUtils.buildAllProjectsIncrementally(ProjectBuildUtils.java:38)
	at tools.vitruv.domains.java.builder.JavaBuildOnEclipseStartup.earlyStartup(JavaBuildOnEclipseStartup.java:20)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:79)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:55)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench$40.run(Workbench.java:2667)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.core.internal.resources.ResourceException: Errors occurred during the build.
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:568)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:603)
	at org.eclipse.core.internal.resources.Project.build(Project.java:124)
	at tools.vitruv.framework.ui.monitorededitor.ProjectBuildUtils.buildIncrementally(ProjectBuildUtils.java:59)
	... 7 more
```

**Comment by jGleitz** [comment]
My bad, wasn’t on latest `master`
